// Collections fournies avec l'application (couvertures dans couv/<id>/<numéro>.jpg).
// « spg » utilise les emplacements historiques de la base (groupes/{code}/numeros).
export const CATALOGUE = [
 {
  "id": "spg",
  "nom": "Super Picsou Géant",
  "court": "SPG",
  "total": 255,
  "couvertures": 256,
  "couleur": "#C62828"
 },
 {
  "id": "tresors",
  "nom": "Les Trésors de Picsou",
  "court": "Trésors",
  "total": 76,
  "couvertures": 76,
  "couleur": "#1E5AA8",
  "titres": {
   "1": "La jeunesse de Picsou",
   "2": "La jeunesse de Picsou",
   "3": "Les trésors de Picsou",
   "4": "Les trésors de Picsou",
   "5": "Les trésors de Picsou",
   "6": "Les trésors de Picsou",
   "7": "Les trésors de Picsou",
   "8": "Les trésors de Picsou",
   "9": "Les trésors de Picsou",
   "10": "Spécial Rapetou",
   "11": "Picsou contre Gripsou",
   "12": "Spécial Gontran",
   "13": "Les trésors de picsou - Castors Juniors",
   "14": "Spécial Donald",
   "15": "Special pirates",
   "16": "Spécial action",
   "17": "Les aventuriers du Grand Nord",
   "18": "Aventures spatiales",
   "19": "Aventuriers des 7 mers",
   "20": "Spécial Fantômes, monstres & zombie",
   "21": "Spécial Géo Trouvetou",
   "22": "Spécial légendes antiques",
   "23": "Spécial en route pour les vacances",
   "24": "Spécial aventures en Asie",
   "25": "Spécial dinosaures et préhistoire",
   "26": "Special Sou Fétiche",
   "27": "Spécial Amérique du Sud",
   "28": "Spécial Vikings !",
   "29": "Spécial Chevaliers !",
   "30": "Spécial Riri, Fifi, Loulou",
   "31": "Aventures dans les îles",
   "32": "Spécial 313- Aventures sur 4 roues",
   "33": "Les trésors de picsou - spécial aventures galactiques",
   "34": "Les trésors de picsou - spécial aventures dans le ciel !",
   "35": "Les trésors de picsou - spécial aventures aquatiques",
   "36": "Aventures dans la Neige",
   "37": "La Jeunesse de Picsou 1",
   "38": "La Jeunesse de Picsou 2",
   "39": "La jeunesse de Picsou 3",
   "40": "La jeunesse de Picsou 4",
   "41": "Les trésors de Picsou : La jeunesse de Picsou, 5è partie",
   "42": "Les trésors de Picsou : La jeunesse de Picsou, 6è partie",
   "43": "Les trésors de Picsou : La jeunesse de Picsou, 7è partie",
   "44": "Int. Don Rosa : 1re Partie 1987/1988",
   "45": "Int. Don Rosa : 2è partie 1988/1989",
   "46": "Les trésors de Picsou : L'intégrale des histoires de Don Ros",
   "47": "Les trésors de picsou : l'intégrale des histoires de don ros",
   "48": "Les trésors de Picsou: l'intégrale des histoires de Don Rosa",
   "49": "Les trésors de Picsous : L'intégrale des histoires de Don Ro",
   "51": "Les trésors de Picsou, 8è partie (1995-1996)",
   "52": "Les trésors de Picsou : L'intégrale des histoires de Don Ros",
   "53": "Les trésors de Picsou : L'intégrale des histoires de Don Ros",
   "54": "Les trésors de Picsou : L'intégrale de Don Rosa 1998-1999",
   "56": "Les trésors de Picsou : L'intégrale de Don Rosa 2000-2001",
   "57": "Les trésors de Picsou : L'intégrale de Don Rosa 2002",
   "58": "Les trésors de Picsou : L'intégrale de Don Rosa 2002",
   "59": "Les trésors de Picsou : L'intégrale de Don Rosa 2003",
   "60": "Les trésors de Picsou : L'intégrale de Don Rosa 2004",
   "61": "Les grands maîtres de la BD Disney",
   "62": "Les grands maîtres de la BD Disney",
   "63": "Les grands maîtres de la BD Disney",
   "64": "Les grands maîtres de la BD Disney",
   "65": "Les grands maîtres de la BD Disney",
   "66": "Les grands maîtres de la BD Disney",
   "67": "Les grands maîtres de la BD Disney",
   "68": "Les grands maîtres de la BD Disney",
   "69": "Les grands maîtres de la BD Disney",
   "70": "Les grands maîtres de la BD Disney",
   "71": "Les grands maîtres de la BD Disney",
   "72": "Les grands maîtres de la BD Disney",
   "73": "Les grands maîtres de la BD Disney",
   "74": "Les grands maîtres de la BD Disney",
   "75": "Les grands maîtres de la BD Disney",
   "76": "Les grands maîtres de la BD Disney",
   "50": "Les trésors de Picsou : L'intégrale des histoires de Don Ros",
   "55": "Les trésors de Picsou : L'intégrale de Don Rosa 1999"
  }
 },
 {
  "id": "doubleduck",
  "nom": "Spécial Double Duck",
  "court": "Double Duck",
  "total": 6,
  "couvertures": 6,
  "couleur": "#263238"
 },
 {
  "id": "dynastie",
  "nom": "L'Histoire de la dynastie Picsou",
  "court": "Dynastie",
  "total": 6,
  "couvertures": 6,
  "couleur": "#8D6E1F",
  "titres": {
   "1": "Tome 1",
   "2": "Tome 2",
   "3": "Tome 3",
   "4": "Tome 4",
   "5": "Tome 5",
   "6": "Tome 6"
  }
 }
];
